### ISSUE TITLE
Outside implementation tester for pseudocode

### ISSUE THREAD

**Issue by mmore500** [mmore500/hstrat-surface-concept#111]
- [ ] tilted site selection
- [ ] stretched site selection
- [ ] steady site selection
- [ ] tilted site lookup
- [ ] stretched site lookup
- [ ] steady site lookup

**Comment by joeymsu** [comment]
- [ ] tilted site selection

**Comment by joeymsu** [comment]
- [ ] tilted site selection
- [ ] stretched site selection
- [ ] steady site selection
- [ ] tilted site lookup
- [ ] stretched site lookup
- [ ] steady site lookup

**Comment by joeymsu** [comment]
[re-written algorithms.zip](https://github.com/user-attachments/files/17218025/re-written.algorithms.zip)

**Comment by joeymsu** [comment]
https://gist.github.com/joeymsu/9b17b0f2748952d7cbb92a142a0ec272

**Comment by mmore500** [comment]
Feedback opened as #133 :ballot_box_with_check:
